services:
  web:
    build: .
    container_name: emotion-api
    ports:
      - "8001:8000"
    networks:
      - emotion-network
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env

  db:
    image: postgres:18-alpine3.22
    container_name: emotion-service-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emotion
    networks:
      - emotion-network
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  emotion-network:
    external: true
