services:
  web:
    build: .
    container_name: emotion-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:18-alpine3.22
    container_name: emotion-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emotion
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
