services:
  web:
    build: .
    container_name: emotion-api
    ports:
      - "8000:8000"
    networks:
      - emotion-network
    volumes:
      - .:/app
    env_file: .env

networks:
  emotion-network:
    external: true
