"""Fix Emotion relationship

Revision ID: f952aa0f0d04
Revises: 5ac7c89a6394
Create Date: 2025-10-18 23:23:24.418448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f952aa0f0d04'
down_revision: Union[str, Sequence[str], None] = '5ac7c89a6394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'emotions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'emotions', type_='unique')
    # ### end Alembic commands ###
